Unit test fixes
central-queensland-uni/moodle-logstore_xapi pull request #34
Opened 2023-07-12 10:27 UTC by ScottVerbeek

Fixes a series of unit tests

2023-07-24 23:52 UTC, rhell4 requested changes

2023-07-24 23:52 UTC, rhell4 commented on src/loader/moodle_curl_lrs.php
>          if(count($statements) > 0) {
This if statement needs to be changed, right now this is checking the array isn't empty and then throwing an exception saying it is empty.

2023-07-24 23:52 UTC, rhell4 commented on tests/enchancement_jisc_skeleton.php
> +    {
Minor thing, Moodle open brackets should be on the same line not a new line.

2023-07-24 23:52 UTC, rhell4 commented on tests/xapi_test_case.php
> +    {
Open brackets should be on the same line.

2023-07-24 23:52 UTC, rhell4 commented on tests/xapi_test_case.php
> +    {
Open brackets should be on the same line.

2023-07-25 00:04 UTC, ScottVerbeek commented on src/loader/moodle_curl_lrs.php
>          if(count($statements) > 0) {
Very good catch. Resolved this.

2023-07-25 00:08 UTC, merged